### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by craddm** [aherbay/erpscope#1]
Hi Alexandre,

The package currently won't install (at least on R 4.0.2 on Linux) - I get the following error.
```
Error in parse(outFile) : 
  /tmp/Rtmp3aZRFY/R.INSTALL147226583e54/erpscope/R/plot_erp.R:32:35: unexpected symbol
31:                                   line_thickness = 0.75 # c(0.75, 1 , 1.25, 1.5),
32:                                   linetype
```

It's a straightforward one - the comma at the end of line 31 is after the comment hash, when it should be before it :)

Cheers,
Matt

**Comment by aherbay** [comment]
Hi Matt,

That's embarrassing haha, I forgot to push some edits on GitHub a while ago including the one causing this error & I should have tested that these days. Thanks a lot for notifying me! Hopefully, the last changes I pushed tonight solve the problem. It seems to work fine now for my installation on MacOS. 
 
Cheers,
Alex

**Comment by craddm** [comment]
I've done it plenty of times! works fine now!

Cheers,
Matt
